name: build
# 触发条件
on:
  push:
    branches:
      - master
  workflow_dispatch: # 允许手动运行，便于调试
# 任务
jobs:
  deploy:
    # 运行的环境
    runs-on: ubuntu-latest
    # 限制主仓库运行
    if: github.repository == 'BUAA-Software-Engineering-2023/ScholarHub-Backend'
    # 步骤
    steps:
      - uses: actions/checkout@v2
      - name: 打包镜像, 上传 Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t scholar-hub .
          docker tag scholar-hub ${{ secrets.DOCKER_REPOSITORY }}
          docker push ${{ secrets.DOCKER_REPOSITORY }}
